/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug  8 2014, 14:49:54                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "string.h"
#include "ADS1110_CTL.h"
#include "delay.h"
#include "AmpGain_CTl.h"
#include "FreqMeasure.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x01)
#define ID_EDIT_0    (GUI_ID_USER + 0x03)
#define ID_TEXT_0    (GUI_ID_USER + 0x04)
#define ID_EDIT_1    (GUI_ID_USER + 0x05)
#define ID_TEXT_1    (GUI_ID_USER + 0x06)
#define ID_EDIT_2    (GUI_ID_USER + 0x07)


// USER START (Optionally insert additional defines)

#define 	 STATE_2V 						4
#define 	 STATE_200MV 					2

#define		 SwitchDisplay(SwitchType)															\
											hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);	\
											Data_Disp = EDIT_GetFloatValue(hItem);				\
																								\
																								\
											hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);	\
																								\
																								\
											if(!strcmp(SwitchType, SWITCH_200mV))				\
											{													\
												Switch_State = STATE_200MV;						\
												EDIT_SetText(hItem,SWITCH_200mV);				\
																								\
												Data_Disp *= 1000; 								\
																								\
											}													\
											else												\
											{													\
												Switch_State = STATE_2V;						\
												EDIT_SetText(hItem,SWITCH_2V);					\
											}													\
																								\
											hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);	\
											EDIT_GetText(hItem, errorStr, 10);				    \
											EDIT_SetFloatMode(hItem, 0.00, 0.0, 2.0, Switch_State, 0);		\
											EDIT_SetFloatValue(hItem, Data_Disp);			\
//											if(isError)											\
//												EDIT_SetText(hItem, ERROR);						\
//											else												\
//											{													\
//												EDIT_SetFloatMode(hItem, 0.00, 0.0, 2.0, Switch_State, 0);		\
//												EDIT_SetFloatValue(hItem, Data_Disp);			\
//											}													\
//											if(!strcmp(errorStr, ERROR))						\
//												EDIT_SetText(hItem, ERROR);						\
//											else												\
//											{													\
//												EDIT_SetFloatMode(hItem, 0.00, 0.0, 2.0, Switch_State, 0);		\
//												EDIT_SetFloatValue(hItem, Data_Disp);			\
//											}													
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

											
											
// USER START (Optionally insert additional static data)


int OldFreq = 0;
static int isError = 0;


// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 2, 0, 320, 240, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Switch", ID_BUTTON_0, 206, 138, 96, 74, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 93, 162, 105, 40, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Frequence:", ID_TEXT_0, 23, 163, 60, 28, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 211, 63, 82, 35, 0, 0x64, 0 },
  { TEXT_CreateIndirect, " Vmax:", ID_TEXT_1, 216, 37, 80, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_2, 16, 27, 178, 94, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

static int Switch_State = STATE_2V;


// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	
 
  //static int TestCounter = 0;
	
  char Switch[10];
  const char* SWITCH_200mV = "200mV";
  const char* SWITCH_2V = "2V";	
  
  const char* ERROR = "NULL";
	
//  static unsigned char Flag = 0;
  unsigned char Ready = 0;
  char * errorStr;
  char * buffStr;

	
   long int Bytes_AD = 0;
  float Data_Disp = 0.0;
	int Frequence = 0;
  
	
	
  // USER END
	 
  switch (pMsg->MsgId) {
	  
//  case WM_PAINT:
//	
//	Bytes_AD = ADS1110_ReadData();
//	EDIT_SetFloatValue(hItem, Bytes_AD);

//	break;
//  
 
	  
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
	EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_SetFont(hItem, &GUI_Font8x16);
    EDIT_SetDecMode(hItem, 0, 0, 100000, 0, 0);
  
	//
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
	EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetText(hItem, "2V");
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_SetFont(hItem, &GUI_Font8x16x3x3);
	EDIT_SetText(hItem, "0.0000");
    // USER START (Optionally insert additional code for further widget initialization)
	
	
	
	
    // USER END
    break;
	
  case WM_TIMER:
	
	//更新测量的频率值
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
	
	Frequence = FreqMeasure();
	if(Frequence != EDIT_GetValue(hItem))
	{	
		EDIT_SetDecMode(hItem, Frequence, 0, 100000, 0, 0);
		EDIT_SetValue(hItem, Frequence);
	}
	
	/*
		当频率大于1800Hz时切换为0.1uF电容，
		当频率小于1800Hz时切换为1uF电容
	*/
	if(Frequence > 1800)		
		GPIO_SetBits(GPIOA, GPIO_Pin_3);
	else
		GPIO_ResetBits(GPIOA, GPIO_Pin_3);
	
	
	

	//更新测量的峰峰值，若ADS1110无应答则不更新并显示示数为0，或者显示“NULL”
	//				   若ADS1110应答数据，则更新数据
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
	
	if(ADS1110_ReadData())
	{	
//		GPIO_ResetBits(GPIOD, GPIO_Pin_2);
//		GUI_Delay(300);
//		GPIO_SetBits(GPIOD, GPIO_Pin_2);
//		GUI_Delay(300);
		Bytes_AD = ADS1110_ReadData();	
		Data_Disp = Bytes_AD / 1000.0;
		
		EDIT_SetDecMode(hItem, Bytes_AD, 0, 2000, 0, 0);
		EDIT_SetValue(hItem, Bytes_AD);			
//		EDIT_SetFloatMode(hItem, Data_Disp, 0.0, 5.0, 4, 0);
//		
//		EDIT_SetFloatValue(hItem, Data_Disp);
		
	}
	else		
	{	
		
		errorStr = "NULL";
		EDIT_SetText(hItem, errorStr);
		isError = 1;
	}
//	if(!Flag)
//	{
//		
//		if(ADS1110_WriteData(CONTINUOUS, RATE_240SPS, PGA_GAIN_1))
//		{	
//			Flag = 0;
//			
//		}	
//		else
//		{	
//			Ready = 1;
//			Flag = 1;
//					
//		}
//	}
//	
//	if(Ready == 1)
//	{
//		Bytes_AD = ADS1110_ReadData();
//		Data_Disp = Bytes_AD * 2.048 / ((-1) * 2048 * 1 );
//					
//		if(Data_Disp != EDIT_GetFloatValue(hItem))
//		{
//			EDIT_SetFloatMode(hItem, Data_Disp, 0.0, 5.0, 4, 0);
//			EDIT_SetFloatValue(hItem, Data_Disp);
//		}	
//	}
//	else
//	{
//		errorStr = "NULL";
//		EDIT_SetText(hItem, errorStr);
//		isError = 1;
//	}
	
//	TestCounter++;
//	EDIT_SetDecMode(hItem, TestCounter, 0, 200000, 1, 0);
//	EDIT_SetValue(hItem, TestCounter);
//  
	
	
	WM_RestartTimer(pMsg->Data.v, 100);
	break;
  
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Switch'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
	  	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1); 	
		EDIT_GetText(hItem,Switch,10);						
		
		if(!strcmp(Switch, SWITCH_200mV))
			strcpy(Switch, SWITCH_2V);		
		else
			strcpy(Switch, SWITCH_200mV);
		

		SwitchDisplay(Switch);
		
	  
		// USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		Frequence = FreqMeasure();
		EDIT_SetDecMode(hItem, Frequence, 0, 100000, 0,0);
		EDIT_SetValue(hItem, Frequence);
	
		GUI_Delay(1);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		
		OldFreq = EDIT_GetValue(hItem);
		EDIT_SetDecMode(hItem, Frequence, 0, 200000, 0,0);
		EDIT_SetValue(hItem, Frequence);
		
		
		
	  
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	  
		
		//if(Data_Disp < 0.2)
		//	SwitchDisplay(SWITCH_200mV);
	  
		
//		Bytes_AD = ADS1110_ReadData();
//		Data_Disp = Bytes_AD * 2.048 / ((-1) * 2048 * 1 );
//		
//		
//		EDIT_SetFloatMode(hItem, 0.00, 0.0, 2.0, 4, 0);
//		EDIT_SetFloatValue(hItem, Data_Disp);
//	  
//	  
		// USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
	  
		
		Bytes_AD = ADS1110_ReadData();
		Data_Disp = Bytes_AD * 2.048 / ((-1) * 2048 * 1 );
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
		EDIT_GetText(hItem, buffStr, 10);
		
		if(strcmp(buffStr, ERROR)){
			if(Data_Disp < 0.3)
				Amp_SetGain(10);
			else if(Data_Disp < 0.01)
				Amp_SetGain(100);
			else if(Data_Disp < 0.001)	
				Amp_SetGain(1000);
		}
		
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;
  WM_HTIMER hTimer;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  hTimer = WM_CreateTimer(WM_GetClientWindow(hWin),0,500,0);

  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
